# Generated by Django 2.2.7 on 2019-11-25 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dinner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('vegetarian', models.BooleanField(default=True)),
                ('ingredients', models.CharField(max_length=255)),
                ('instructions', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('time', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Drinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home', models.BooleanField(default=True)),
                ('alcoholic', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('time', models.IntegerField()),
                ('location', models.CharField(max_length=255)),
                ('ingredients', models.CharField(max_length=255)),
                ('instructions', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('time', models.IntegerField()),
                ('location', models.CharField(max_length=255)),
            ],
        ),
    ]
